version: '3.8'

services:
  api:
    build:
      context: ./api
      target: ci
    depends_on:
      - db_test
    environment:
      - DATABASE_TEST_URL=mysql://root:root@db_test:3306/trello_test

  db_test:
    build: ./mysql_test
    image: mysql:8.0
    platform: linux/x86_64
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 5s
      retries: 10
