version: '3.8'

services:
  db:
    build: ./mysql
    image: mysql:8.0
    ports:
      - 3306:3306
    volumes:
      # - db_data:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 5s
      retries: 10

  db_test:
    build: ./mysql_test
    image: mysql:8.0
    expose:
      - 3306
    volumes:
      # - db_data:/var/lib/mysql
      - ./mysql_test:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 5s
      retries: 10

  api:
    build: ./api
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 4000:4000
    command: npm run start:watch
    volumes:
      - ./api/src:/app/src
      - /api/node_modules/

  web:
    build: ./web
    ports:
      - 3000:3000
    command: npm start
    volumes:
      - ./web/src:/app/src
      - /web/node_modules

volumes:
  db_data:
