version: '3.8'

services:
  db:
    platform: linux/x86_64
    build: ./mysql
    image: mysql:8.0
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 5s
      retries: 10
    container_name: db

  db_test:
    platform: linux/x86_64
    build: ./mysql_test
    image: mysql:8.0
    expose:
      - 3306
    volumes:
      - ./mysql_test:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 5s
      retries: 10
    container_name: db_test

  api:
    build:
      context: ./api
      target: development
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 4000:4000
    command: npm run start:watch
    volumes:
      - ./api/src:/app/src
      - /api/node_modules/
    container_name: api

  web:
    build:
      context: ./web
      target: development
    ports:
      - 3000:3000
    command: npm start
    volumes:
      - ./web/src:/app/src
      - /web/node_modules
    container_name: web

volumes:
  db_data: