version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root

  api:
    build: ./api
    depends_on:
      - db
    ports:
      - 4000:4000
    command: npm start
    volumes:
      - ./api/src/:/app/src/
      - ./api/node_modules/

  web:
    build: ./web
    ports:
      - 8080:3000
    command: npm start
    volumes:
      - ./web/src/:/app/src/
      - ./web/node_modules
