name: CI checks
on: push
s
jobs:
  test-client:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2gi
      - name: Goto client and run tests
        run: cd api && npm i && npm test
