name: CI checks
on: push

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build API, run CI checks
        run: cd api && npm i && docker-compose exec api npm run test:watch
