name: CI checks
on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker-compose -f docker-compose.yml up --build

      - name: unit test
        run: cd ./api && docker-compose exec api npm run test:watch
